### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Senbei123** [gregod/addon-usbhid-to-mqtt#1]
Hi,

I found this repro to get my Neuftech USB Reader for RFID working with my home assistant instance.

I download all files and put them unter an own folder in the custom_component folder.
Then I restart home assistant - but nothing happend. Nothing showed up and even the log doesn't show anything.

Could you help me pointing in the right direction?

Thanks in advance.

BR,
Senbei

**Comment by gregod** [comment]
Hi,
this addon is packaged as a [hassio / homeassistant os addon](https://www.home-assistant.io/addons/)
To install it you need [to add](https://www.home-assistant.io/hassio/installing_third_party_addons/) my repository https://github.com/gregod/hassio-addon-repo  under supervisor / "Add-on store" and then activate this addon. 
Unfortunately it is not available for a plain installation under custom_components. 
Hope that helps.
